// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using fam_comfort.Persistence;

#nullable disable

namespace fam_comfort.Persistence.Migrations
{
    [DbContext(typeof(FamComfortDbContext))]
    partial class FamComfortDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("fam_comfort.Core.Models.Color", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FacadeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(256)");

                    b.Property<string>("PathToImage")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(2048)")
                        .HasDefaultValue("images/template_image_facade.png");

                    b.HasKey("Id");

                    b.HasIndex("FacadeId");

                    b.ToTable("Colors", (string)null);
                });

            modelBuilder.Entity("fam_comfort.Core.Models.Decor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DecorCategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("varchar(1024)");

                    b.Property<int>("Height")
                        .HasColumnType("int");

                    b.Property<int>("Length")
                        .HasColumnType("int");

                    b.Property<string>("Materials")
                        .IsRequired()
                        .HasColumnType("varchar(256)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(256)");

                    b.Property<string>("PathToImageSchema")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(2048)")
                        .HasDefaultValue("images/template_image_facade.png");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasColumnType("varchar(128)");

                    b.Property<int>("Width")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DecorCategoryId");

                    b.ToTable("Decors", (string)null);
                });

            modelBuilder.Entity("fam_comfort.Core.Models.DecorCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(256)");

                    b.Property<string>("PathToImage")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(2048)")
                        .HasDefaultValue("images/template_image_facade_category.png");

                    b.HasKey("Id");

                    b.ToTable("DecorCategories", (string)null);
                });

            modelBuilder.Entity("fam_comfort.Core.Models.Facade", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("varchar(1024)");

                    b.Property<Guid>("FacadeCategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Height")
                        .HasColumnType("int");

                    b.Property<int>("Length")
                        .HasColumnType("int");

                    b.Property<string>("Materials")
                        .IsRequired()
                        .HasColumnType("varchar(256)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(256)");

                    b.Property<string>("PathToImageSchema")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(2048)")
                        .HasDefaultValue("images/template_image_facade.png");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasColumnType("varchar(128)");

                    b.Property<int>("Width")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FacadeCategoryId");

                    b.ToTable("Facades", (string)null);
                });

            modelBuilder.Entity("fam_comfort.Core.Models.FacadeCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(256)");

                    b.Property<string>("PathToImage")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(2048)")
                        .HasDefaultValue("images/template_image_facade_category.png");

                    b.HasKey("Id");

                    b.ToTable("FacadeCategories", (string)null);
                });

            modelBuilder.Entity("fam_comfort.Core.Models.Color", b =>
                {
                    b.HasOne("fam_comfort.Core.Models.Facade", "Facade")
                        .WithMany("Colors")
                        .HasForeignKey("FacadeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Facade");
                });

            modelBuilder.Entity("fam_comfort.Core.Models.Decor", b =>
                {
                    b.HasOne("fam_comfort.Core.Models.DecorCategory", "DecorCategory")
                        .WithMany("Decors")
                        .HasForeignKey("DecorCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DecorCategory");
                });

            modelBuilder.Entity("fam_comfort.Core.Models.Facade", b =>
                {
                    b.HasOne("fam_comfort.Core.Models.FacadeCategory", "FacadeCategory")
                        .WithMany("Facades")
                        .HasForeignKey("FacadeCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FacadeCategory");
                });

            modelBuilder.Entity("fam_comfort.Core.Models.DecorCategory", b =>
                {
                    b.Navigation("Decors");
                });

            modelBuilder.Entity("fam_comfort.Core.Models.Facade", b =>
                {
                    b.Navigation("Colors");
                });

            modelBuilder.Entity("fam_comfort.Core.Models.FacadeCategory", b =>
                {
                    b.Navigation("Facades");
                });
#pragma warning restore 612, 618
        }
    }
}
